# Generated by Django 4.1.3 on 2022-12-03 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lapangan',
            name='jam_buka',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='lapangan',
            name='jam_tutup',
            field=models.TimeField(default=datetime.time(23, 0)),
        ),
    ]
