# Generated by Django 4.1.3 on 2022-12-09 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_reservasi_jadwal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservasi',
            name='jadwal',
        ),
        migrations.AddField(
            model_name='jadwal',
            name='reservasi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.reservasi'),
        ),
    ]
