# Generated by Django 4.1.3 on 2022-12-10 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_jadwal_reservasi_reservasi_totalharga_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RekeningPayKuy',
            fields=[
                ('penyewa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='database.penyewa')),
                ('saldo', models.BigIntegerField(default=0)),
            ],
        ),
    ]
