# Generated by Django 4.1.3 on 2022-12-10 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_remove_reservasi_jadwal_jadwal_reservasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservasi',
            name='lapangan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.lapangan'),
        ),
        migrations.AlterField(
            model_name='reservasi',
            name='penyewa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.penyewa'),
        ),
    ]
