# Generated by Django 4.1.3 on 2022-12-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_rekeningpaykuy'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservasi',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
