# Generated by Django 4.1.3 on 2022-12-10 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_alter_reservasi_totalharga'),
        ('database', '0006_reservasi_is_paid'),
    ]

    operations = [
    ]
